# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('0', 'Requested'), ('1', 'Progressing'), ('2', 'Done')], max_length=1)),
                ('type', models.CharField(max_length=100)),
                ('resource', models.URLField()),
                ('result', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField()),
            ],
        ),
    ]
