# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-28 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20170928_2000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resolved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.TextField(blank=True, null=True),
        ),
    ]
