# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_auto_20170928_2003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='type',
            field=models.CharField(default='ocr', max_length=100),
        ),
    ]
