# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20171001_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='result',
            field=models.TextField(blank=True, default=''),
        ),
    ]
