# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_auto_20171001_2318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resource',
            field=models.TextField(blank=True, default=''),
        ),
    ]
