# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-08 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20171008_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='resource',
            field=models.CharField(max_length=250),
        ),
    ]
